generatorName: typescript-axios
cleanupOutput: true
inputSpec: http://localhost:4002/api/connectors-docs-json 
useSingleRequestParameter: true
enumPropertyNaming: 'UPPERCASE'
outputDir: ./libs/api/src/connections
additionalProperties:
  supportsES6: true
  